version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/:/app
    networks:
      - app-network
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge